---
title: "Changing Minds on Gay Marriage"
output:
  pdf_document: default
  html_document: default
---

In this exercise, we analyze the data from two experiments in which
households were canvassed for support on gay marriage.

This exercise is based on: LaCour, M. J., and
D. P. Green. 2014. “[When Contact Changes Minds: An Experiment on
Transmission of Support for Gay
Equality.](http://dx.doi.org/10.1126/science.1256151)” *Science*
346(6215): 1366–69.

Note that the original study was later retracted due to allegations of
fabricated data.  We will revisit this issue in the follow-up
exercise.  In this exercise, however, we analyze the original data
while ignoring the allegations.

Canvassers were given a script leading to conversations that averaged
about twenty minutes.  A distinctive feature of this study is that gay
and straight canvassers were randomly assigned to households and
canvassers revealed whether they were straight or gay in the course of
the conversation.  The experiment aims to test the 'contact
hypothesis,' which contends that out-group hostility (towards gays in
this case) diminishes when people from different groups interact with
one another.

The data file is `gay.csv`, which is a CSV
file. The names and descriptions of
variables are:

 -------------------- ----------------------------------------------------------
 Name                 Description
 -------------------- ----------------------------------------------------------
 `study`              Study (1 or 2) 
 
 `treatment`          Treatment assignment: `No contact`, 
                      `Same-Sex Marriage Script by Gay Canvasser`,
                      `Same-Sex Marriage Script by Straight Canvasser`,
                      `Recycling Script by Gay Canvasser`, and
                      `Recycling Script by Straight Canvasser`
 
 `wave`               Survey wave (1-7). Note that Study 2 lacks wave 5 and 6.
 
 `ssm`                Support for gay marriage (1 to 5).  
                      Higher scores indicate more support.
 -------------------------------------------------------------------------------

Each observation of this data set is a respondent giving a response to
a five-point survey item on same-sex marriage.  There are two
different studies in this data set, involving interviews during 7
different time periods (i.e. 7 waves).  In both studies, the first
wave consists of the interview before the canvassing treatment occurs.

## Question 1

Using the baseline interview wave before the treatment is
  administered, examine whether randomization was properly conducted.
  Base your analysis on the three groups of Study 1: 'Same-Sex
  Marriage Script by Gay Canvasser,' 'Same-Sex Marriage Script by
  Straight Canvasser' and 'No Contact.'  Briefly comment on the
  results.

## Question 2

The second wave of survey was implemented two months after the
  canvassing.  Using Study 1, estimate the average treatment effects
  of gay and straight canvassers on support for same-sex marriage,
  separately.  Give a brief interpretation of the results.

## Question 3

The study contained another treatment that involves contact, but
  does not involve using the gay marriage script.  Specifically, the
  authors used a script to encourage people to recycle.  What is the
  purpose of this treatment?  Using Study 1 and wave 2, compare
  outcomes from the treatment 'Same-Sex Marriage Script by Gay
  Canvasser' to 'Recycling Script by Gay Canvasser.'  Repeat the
  same for straight canvassers, comparing the treatment 'Same-Sex
  Marriage Script by Straight Canvasser' to 'Recycling Script by
  Straight Canvasser.'  What do these comparisons reveal?  Give a
  substantive interpretation of the results.

## Question 4

In Study 1, the authors reinterviewed the respondents 6
  different times (in waves 2 to 7) after treatment, at two month
  intervals.  The last interview in wave 7 occurs one year after
  treatment.  Do the effects of canvassing last?  If so, under what
  conditions?  Answer these questions by separately computing the
  average effects of straight and gay canvassers with the same-sex
  marriage script for each of the subsequent waves (relative to the
  control condition).

## Question 5

The researchers conducted a second study to replicate the core
  results of the first study.  In this study, same-sex marriage
  scripts are only given by gay canvassers.  For Study 2, use the
  treatments 'Same-Sex Marriage Script by Gay Canvasser' and 'No
  Contact' to examine whether randomization was appropriately
  conducted.  Use the baseline support from wave 1 for this analysis.
 
## Question 6

For Study 2, estimate the treatment effects of gay canvassing
  using data from wave 2.  Are the results consistent with those of
  Study 1?

## Question 7

Using Study 2, estimate the average effect of gay canvassing at
  each subsequent wave and observe how it changes over time.  Note
  that Study 2 did not have 5th or 6th wave, but the 7th wave occurred
  one year after treatment as in Study 1.  Draw an overall conclusion
  from both Study 1 and Study 2.

