\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{longtable,booktabs}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={The Mark of a Criminal Record Revisited},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{0}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{The Mark of a Criminal Record Revisited}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\maketitle


In one of the additional exercises for Chapter 2, we analyzed data from
an important field experiment by Devah Pager about the the effect of
race and criminal record on employment:

\href{https://dx.doi.org/10.1086/374403}{``The Mark of a Criminal
Record''}. \emph{American Journal of Sociology} 108(5):937-975. Look
\href{https://youtu.be/nUZqvsF_Wt0}{here} to watch Professor Pager
discuss the design and result.

This is a follow-up exercise using the same data set. Last time you
encountered the paper, you described the different callback rates
between groups. Now we are going to use what we've learned about
statistical inference to better understand those patterns. You are
welcome---and even encouraged---to reuse code from that exercise. In
fact, in practice you often have to work with the same dataset many
times, and writing good code the first time helps you reuse the code in
future projects.

The dataset is called \texttt{criminalrecord.csv}. You may not need to
use all of these variables for this activity. We've kept these
unnecessary variables in the dataset because it is common to receive a
dataset with much more information than you need.

\begin{longtable}[c]{@{}ll@{}}
\toprule\addlinespace
\begin{minipage}[b]{0.19\columnwidth}\raggedright
Name
\end{minipage} & \begin{minipage}[b]{0.75\columnwidth}\raggedright
Description
\end{minipage}
\\\addlinespace
\midrule\endhead
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{jobid}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
Job ID number
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{callback}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
\texttt{1} if tester received a callback, \texttt{0} if the tester did
not receive a callback.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{black}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
\texttt{1} if the tester is black, \texttt{0} if the tester is white.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{crimrec}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
\texttt{1} if the tester has a criminal record, \texttt{0} if the tester
does not.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{interact}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
\texttt{1} if tester interacted with employer during the job
application, \texttt{0} if tester doesn't interact with employer.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{city}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
\texttt{1} is job is located in the city center, \texttt{0} if job is
located in the suburbs.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{distance}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
Job's average distance to downtown.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{custserv}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
\texttt{1} if job is in the costumer service sector, \texttt{0} if it is
not.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{manualskill}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
\texttt{1} if job requires manual skills, \texttt{0} if it does not.
\end{minipage}
\\\addlinespace
\bottomrule
\end{longtable}

The problem will give you practice with:

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  re-using old code (optional)
\item
  constructing confidence intervals
\item
  difference-of-means tests
\item
  p-values
\item
  type I and type II errors
\end{itemize}

\subsection{Question 1}\label{question-1}

Begin by loading the data into R and explore the data. How many cases
are there in the data? Run \texttt{summary()} to get a sense of things.
In how many cases is the tester black? In how many cases is he white?

\subsection{Answer}\label{answer}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{audit <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"data/criminalrecord.csv"}\NormalTok{)}

\NormalTok{## (1) Number of observations}
\KeywordTok{dim}\NormalTok{(audit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 696   9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## (2) quick summary}
\KeywordTok{summary}\NormalTok{(audit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      jobid            callback          black          crimrec      
##  Min.   :   1.00   Min.   :0.0000   Min.   :0.000   Min.   :0.0000  
##  1st Qu.:  87.75   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000  
##  Median :1024.50   Median :0.0000   Median :1.000   Median :0.0000  
##  Mean   : 658.57   Mean   :0.1638   Mean   :0.569   Mean   :0.4986  
##  3rd Qu.:1112.25   3rd Qu.:0.0000   3rd Qu.:1.000   3rd Qu.:1.0000  
##  Max.   :1200.00   Max.   :1.0000   Max.   :1.000   Max.   :1.0000  
##                                                                     
##     interact           city           distance        custserv     
##  Min.   :0.0000   Min.   :0.0000   Min.   : 0.00   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.: 8.00   1st Qu.:0.0000  
##  Median :0.0000   Median :0.0000   Median :12.00   Median :1.0000  
##  Mean   :0.2428   Mean   :0.3919   Mean   :11.96   Mean   :0.6282  
##  3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:16.00   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :25.00   Max.   :1.0000  
##                   NA's   :2        NA's   :2       NA's   :2       
##   manualskill    
##  Min.   :0.0000  
##  1st Qu.:0.0000  
##  Median :0.0000  
##  Mean   :0.4813  
##  3rd Qu.:1.0000  
##  Max.   :1.0000  
##  NA's   :2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## (3) White and black}
\KeywordTok{length}\NormalTok{(audit$jobid[audit$black ==}\StringTok{ }\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 396
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(audit$jobid[audit$black ==}\StringTok{ }\DecValTok{0}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 300
\end{verbatim}

There are 696 observations. There are 396 cases with black applicants
and 300 cases with white applicants.

\subsection{Question 2}\label{question-2}

Now we examine the central question of the study. Calculate the
proportion of callbacks for white applicants with a criminal record,
white applicants without a criminal record, black applicants with a
criminal record, and black applicants without a criminal record.

\subsection{Question 3}\label{question-3}

Now consider the callback rate for white applicants with a criminal
record. Construct a 95\% confidence interval around this estimate. Also,
construct a 99\% confidence interval around this estimate.

\subsection{Question 4}\label{question-4}

Calculate the estimated effect of a criminal record for white applicants
by comparing the callback rate in the treatment condition and the
callback rate in the control condition. Create a 95\% confidence
interval around this estimate. Next, describe the estimate and
confidence interval in a way that could be understood by a general
audience.

\subsection{Question 5}\label{question-5}

Assuming a null hypothesis that there is no difference in callback rates
between white people with a criminal record and white people without a
criminal record, what is the probability that we would observe a
difference as large or larger than the one that we observed in a sample
of this size?

\subsection{Question 6}\label{question-6}

Imagine that we set up a hypothesis test where the null hypothesis is
that there is no difference in callback rates between whites with and
without a criminal record. In the context of this problem, what would it
mean to commit a type I error? In the context of this problem, what
would it mean to commit a type II error? If we set $\alpha = 0.05$ for a
two-tailed test are we specifying the probability of type I error or
type II error?

\end{document}
