\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{longtable,booktabs}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Revisiting the 2016 US Presidential Election},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{0}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Revisiting the 2016 US Presidential Election}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\maketitle


In the 2016 US presidential election, the Republican candidate Donald
Trump surprised many by defeating the Democratic candidate Hillary
Clinton. In particular, even right before the election, polls were
predicting that Hillary Clinton would win the election by a comfortable
margin. Why did preelection polls fail to predict the election outcome?
We analyze the polling data, taken from
\href{http://elections.huffingtonpost.com/pollster\#2016-general-election}{Hufftington
post}, that include the most recent polls leading up to the election.
The dataset we will be analyzing (\texttt{polls2016.csv}) has 1395
observations, each representing a different poll, and includes the
following variables:

\begin{longtable}[c]{@{}ll@{}}
\toprule\addlinespace
\begin{minipage}[b]{0.24\columnwidth}\raggedright
Name
\end{minipage} & \begin{minipage}[b]{0.70\columnwidth}\raggedright
Description
\end{minipage}
\\\addlinespace
\midrule\endhead
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{id}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
Poll ID
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{state}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
U.S. state where poll was fielded
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{Clinton}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
The poll's estimated level of support for Hillary Clinton
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{Trump}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
The poll's estimated level of support for Donald Trump
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{Undecided}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
The poll's estimated percentage of undecided voters
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{days\_to\_election}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
Number of days before November 4, 2016.
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{electoral\_votes}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
Number of electoral votes allocated to the state where the poll was
fielded (a state-level variable)
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{sample\_size}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
The number of people surveyed in the poll
\end{minipage}
\\\addlinespace
\bottomrule
\end{longtable}

We will also analyze a dataset (\texttt{election2016.csv}) which
contains the state-by-state voteshare for each candidate collected from
CNN. This data set has the following variables:

\begin{longtable}[c]{@{}ll@{}}
\toprule\addlinespace
\begin{minipage}[b]{0.24\columnwidth}\raggedright
Name
\end{minipage} & \begin{minipage}[b]{0.70\columnwidth}\raggedright
Description
\end{minipage}
\\\addlinespace
\midrule\endhead
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{State}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
U.S. state where poll was fielded
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{Clinton}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
The percent of votes Clinton received
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.24\columnwidth}\raggedright
\texttt{Trump}
\end{minipage} & \begin{minipage}[t]{0.70\columnwidth}\raggedright
The percent of votes Trump received
\end{minipage}
\\\addlinespace
\bottomrule
\end{longtable}

\subsection{Question 1}\label{question-1}

We will begin by calculating the predicted vote share for Hillary
Clinton by using the average support rate of the most recent (based on
the \texttt{days\_to\_election} variable) polls for each state. If there
are multiple polls on the same day, use the average sample size. What is
the bias of prediction across states? What is the root mean squared
error? Create a histogram of prediction error. Briefly interpret these
results.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{results <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"data/election2016.csv"}\NormalTok{)}
\NormalTok{polls <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"data/polls2016.csv"}\NormalTok{)}
\NormalTok{state.names <-}\StringTok{ }\KeywordTok{unique}\NormalTok{(polls$state)}

\NormalTok{## Predictions for Clinton}
\NormalTok{n <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\DecValTok{51}\NormalTok{)}
\NormalTok{poll.pred.C <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\DataTypeTok{nrow =} \DecValTok{51}\NormalTok{, }\DataTypeTok{ncol =} \DecValTok{3}\NormalTok{)}
\KeywordTok{row.names}\NormalTok{(poll.pred.C) <-}\StringTok{ }\KeywordTok{as.character}\NormalTok{(state.names)}
\NormalTok{for (i in }\DecValTok{1}\NormalTok{:}\DecValTok{51}\NormalTok{) \{}
  \NormalTok{## subset the ith state}
  \NormalTok{state.data <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(polls, }\DataTypeTok{subset =} \NormalTok{(state ==}\StringTok{ }\NormalTok{state.names[i]))}
  \NormalTok{## subset the latest polls within the state}
  \NormalTok{latest <-}\StringTok{ }\NormalTok{state.data$days_to_election ==}\StringTok{ }\KeywordTok{min}\NormalTok{(state.data$days_to_election) }
  \NormalTok{## compute the mean of latest polls and store it}
  \NormalTok{poll.pred.C[i, }\DecValTok{1}\NormalTok{] <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(state.data$Clinton[latest])}
  \NormalTok{n[i] <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(state.data$sample_size[latest])}
\NormalTok{\}}

\NormalTok{## Calculate Bias}
\NormalTok{Clinton.bias <-}\StringTok{ }\NormalTok{poll.pred.C[,}\DecValTok{1}\NormalTok{] -}\StringTok{ }\NormalTok{results$Clinton}
\KeywordTok{mean}\NormalTok{(Clinton.bias)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.01672549
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## Root Mean Squared Error}
\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{mean}\NormalTok{((Clinton.bias)^}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.03820633
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## Histogram of Bias}
\KeywordTok{hist}\NormalTok{(Clinton.bias, }\DataTypeTok{xlab =} \StringTok{"Prediction Error"}\NormalTok{,}
     \DataTypeTok{main =} \StringTok{"Histogram of Clinton's Prediction Error"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{election-2016_files/figure-latex/unnamed-chunk-1-1.pdf}

The polls under-predicted her voteshare by only 1.67 percentage points.
The RMSE is around 3.82 percentage points which tells us there is a
substantial amount of variation in the prediction error. Additionally
the histogram demonstrates that the prediction error is pretty evenly
distributed around 0. In other words, the bias is relatively small.

\subsection{Question 2}\label{question-2}

Construct 95\% confidence intervals for each of the state-level
predictions obtained in the previous question. Plot the prediction
against the true result with a 45-degree line to indicate whether the
polls under or over predicted Clinton's voteshare. What proportion of
the actual election results are contained within these confidence
intervals? Does the coverage improve if we correct for the bias of
prediction obtained in the previous question? Briefly interpret your
results.

\subsection{Question 3}\label{question-3}

Repeat the analysis from Questions 1 and 2 for Donald Trump. Compare and
interpret your results.

\subsection{Question 4}\label{question-4}

We will now explore one hypothesis for Trump's surprising victory in the
election: a large proportion of voters whom polls classified as
``undecided'' cast ballots for Trump on the election day. These voters
may not have wanted to admit they supported Trump when answering
surveys. It is also possible that they made up their minds right before
the election following the FBI announcements. Although we do not have
individual data necessary for directly testing this hypothesis, we will
predict Trump's electoral college votes under the assumption that all
undecided voters voted for Trump. Specifically, run 1000 Monte Carlo
simulations under this assumption by computing the probability of
winning each state $j$ for Trump as follows:

$P(\text{Trump wins state } j) = P(Z_j  > 0.5)$

where $Z_j$ is a Normal random variable with mean $\hat{p}_j$ and
standard deviation $\sqrt{\hat{p}_j(1-\hat{p}_j)/n_j}$ with $n_j$ being
the sample size of the latest poll for that state and

$\hat{p}_j = \frac{\text{Trump supporters + undecided respondents}}{\text{Trump supporters + Clinton supporters + undecided respondents}}$

Simulate Trump's electoral vote outcomes by sampling its winner using
the above probability. In other words, first calculate $\hat{p}_j$ for
each state $j$, then run a simulation where you sample whether Trump
wins that state using a draw from a Bernoulli Distribution with the
probability of success equal to the above probability
$P(\text{Trump wins state } j)$. Present the results using a histogram
with a red vertical line representing the actual outcome (Trump = 306).
Additionally report the point estimate, standard error, and its 95\%
confidence interval for the total number of electoral votes for Trump.

\end{document}
