---
title: "Government Transfer and Poverty Reduction in Brazil"
output: 
  html_document
---

This exercise is based on
Litschig, Stephan, and Kevin M Morrison. 2013. “[The Impact of Intergovernmental Transfers on Education Outcomes and Poverty Reduction.](http://dx.doi.org/10.1257/app.5.4.206)” *American Economic Journal: Applied Economics* 5(4): 206–40. 

In this exercise, we estimate the effects of increased government
spending on educational attainment, literacy, and poverty
rates.

Some
scholars argue that government spending accomplishes very little in
environments of high corruption and inequality. Others suggest that in
such environments, accountability pressures and the large demand for
public goods will drive elites to respond.  To address this debate, we
exploit the fact that until 1991, the formula for government transfers
to individual Brazilian municipalities was determined in part by the
municipality's population. This meant that municipalities with
populations below the official cutoff did not receive additional
revenue, while states above the cutoff did.  The data set
`transfer.csv` contains the variables:

--------------------------------------------------------------------------------
 Name                Description
 ------------------- ---------------------------------------------------------
 `pop82`             Population in 1982
 
 `poverty80`         Poverty rate of state in 1980
 
 `poverty91`         Poverty rate of state in 1991
 
 `educ80`            Average years education of state in 1980
 
 `educ91`            Average years education of state in 1991
 
 `literate91`        Literacy rate of state in 1991
 
 `state`             State
 
 `region`            Region
 
 `id`                Municipal ID
 
 `year`              Year of measurement
--------------------------------------------------------------------------------

## Question 1

We will apply the regression discontinuity design to this
  application.  State the required assumption for this design and
  interpret it in the context of this specific application.  What
  would be a scenario in which this assumption is violated?  What are
  the advantages and disadvantages of this design for this specific
  application?

## Question 2

Begin by creating a variable that determines how close each
  municipality was to the cutoff that determined whether states
  received a transfer or not. Transfers occurred at three separate
  population cutoffs: 10,188, 13,584, and 16,980. Using these cutoffs,
  create a single variable that characterizes the difference from the
  closest population cutoff.  Following the original analysis,
  standardize this measure by dividing the difference with the
  corresponding cutoff and multiply it by 100.  This will yield a
  normalized percent score for the difference between the population
  of each state and the cutoff relative to the cutoff value.

## Question 3

Begin by subsetting the data to include
  only those municipalities within 3 points of the funding cutoff on
  either side.  Using regressions, estimate the average causal effect
  of government transfer on each of the three outcome variables of
  interest: educational attainment, literacy, and poverty.  Give a
  brief substantive interpretation of the results.

## Question 4

Visualize the analysis done in the previous question by plotting
  data points, fitted regression lines, and the population threshold.
  Briefly comment on the plot.

## Question 5
Instead of fitting linear regression models, we compute the
  difference in means of the outcome variables between the groups of
  observations above the threshold and below it.  How do the estimates
  differ from what you obtained in the earlier Question?  Is
  the assumption invoked here identical to the one required for the
  analysis conducted there?  Which
  estimates are more appropriate?  Discuss.

## Question 6

Repeat the analysis conducted in the original question
  but vary the width of analysis window from 1 to 5 percentage points
  below and above the threshold.  Obtain the estimate for every
  percentage point.  Briefly comment on the results.

## Question 7

Conduct the same analysis as in the
  earlier Question but this time using measures of the
  poverty rate and educational attainment taken in 1980, before the
  population-based government transfers began. What do the results
  suggest about the validity of analysis presented in
  the earlier Question?
