---
title: "Predicting Elections with Linear Models"
output: pdf_document
---

Earlier in the chapter, we studied the prediction of election outcomes
using polls.  Here, we study the prediction of election outcomes based
on betting markets.  In particular, we analyze data for the 2008 and
2012 US presidential elections from the online betting company,
Intrade.  At Intrade, people trade contracts such as 'Obama to win
the electoral votes of Florida.'  Each contract's market price
fluctuates based on its sales.  Why might we expect betting markets
like Intrade to accurately predict the outcomes of elections or of
other events?  Some argue that the market can aggregate available
information efficiently.  In this exercise, we will test this 
*efficient market hypothesis* by analyzing the market prices of
contracts for Democratic and Republican nominees' victories in each
state.

The data files for 2008 is available in CSV format as
`intrade08.csv`. The variables in these datasets are:

 Name                Description
 ------------------- ---------------------------------------------------------
 `day`               Date of the session 
 `statename`         Full name of each state (including District of Columbia in 2008) 
 `state`             Abbreviation of each state (including District of Columbia in 2008)
 `PriceD`            Closing price (predicted vote share) of Democratic Nominee's market
 `PriceR`            Closing price (predicted vote share) of Republican Nominee's market 
 `VolumeD`           Total session trades of Democratic Party Nominee's market
 `VolumeR`           Total session trades of Republican Party Nominee's market 

Each row represents daily trading
information about the contracts for either the Democratic or
Republican Party nominee's victory in a particular state. 

We will also
use the election outcome data.  This data file is `pres08.csv` with variables:

 Name                 Description
 -------------------- ---------------------------------------------------------
 `state.name`         Full name of state (only in `pres2008`)
 `state`              Two letter state abbreviation
 `Obama`              Vote percentage for Obama
 `McCain`             Vote percentage for McCain
 `EV`                 Number of electoral college votes for this state
 
We'll also use poll data from 2008 in the file `polls08.csv`,  The variables in the polling data are:
  
 Name                 Description
 -------------------- ---------------------------------------------------------
 `state`              Abbreviated name of state in which poll was conducted 
 `Obama`              Predicted support for Obama (percentage)
 `Romney`             Predicted support for Romney (percentage) 
 `Pollster`           Name of organization conducting poll 
 `middate`            Middle of the period when poll was conducted 

What is the relationship between the price margins of the Intrade market and the actual margin of victory? Using only the market data from the day before the election in 2008, regress Obama’s actual margin of victory in each state on Obama’s price margin from the Intrade markets. We’ll start by constructing Obama’s Intrade margin from 2008

## Question 1

Load the Intrade and Election outcome data for 2008 and merge them together.

Create a `DaysToElection` variable by subtracting the day of the election from each day in the dataset.  Now create a state margin of victory variable to predict, and a betting market margin to predict it with.

## Question 2

Considering only the trading one day from the election, predict the actual electoral margins from the trading margins using a linear model.  Does it predict well? How would you visualize the predictions and the outcomes together?  Hint: because we only have one predictor you can use `abline`.

## Question 3

Even efficient markets aren’t omniscient. Information comes in about the election every day and the market prices should reflect any change in information that seem to matter to the outcome.

We can examine how and about what the markets change their minds by looking at which states they are confident about, and which they update their ‘opinions’ (i.e. their prices) about. Over the period before the election, let’s see how prices for each state are evolving. We can get a compact summary of price movement by fitting a linear model to Obama’s margin for each state over the 20 days before the election.

We will summarise price movement by the direction (up or down) and rate of change (large or small) of price over time. This is basically also what people in finance do, but they get paid more…

Start by plotting Obama’s margin in West Virginia against the number of days until the election and modeling the relationship with a linear model.  Use the last 20 days.  Show the model's predictions on each day and the data.  What does this model's slope coefficient tells us about which direction the margin is changing and also how fast it is changing? Hint: West Virginia is 50th on the alphabetical list of state names.

## Question 4 

Now do it for all states and collect the slop coefficients to see how volative the state estimates are

## Question 5

Now predict the winner of the election *one week before the election* using the Intrade data. To do so, first use the *two weeks before* that moment to fit state level linear models, then use those models to predict what will happen in each state.  How well does the model do predicting the election outcome?

