\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{longtable,booktabs}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Inequality of Success in Online Music Markets},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{0}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Inequality of Success in Online Music Markets}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\maketitle


The Music Lab Project is a web based randomized experiment designed to
investigate the role of social influence in the market success of songs.
This project examines whether songs becomes ``hits'' not only because of
their inherent \emph{musical} qualities but also because of a
\emph{social} process: when people hear that a song is popular, they
become more inclined to like the song themselves. This exercise is in
part based on:

Salganik, Matthew J., Peter Sheridan Dodds and Duncan J. Watts. 2006.
``\href{http://dx.doi.org/10.1126/science.1121066}{Experimental Study of
Inequality and Unpredictability in an Artificial Cultural Market.}''
\emph{Science} 311(5762): 854-856.

Two experiments were conducted in this study using a web platform called
\emph{Music Lab} where users listen to music, rate it, and optionally
download songs of their choice. For this exercise, we use a subset of
the original data and focus on a smaller number of treatment conditions.
In \textbf{Experiment 1}, users were shown a list of previously unknown
songs of unknown music bands. They were randomly assigned to one of two
conditions: \emph{Independent} and \emph{Social influence}. In the
\emph{Independent} condition, users decide which songs to listen to
based on their titles and the names of the bands alone. After listening
to songs, they were asked to rate each of them (from one star for ``I
hate it'', to five stars for ``I love it''). Finally, they have an
option to download any of the songs they listened to. In the
\emph{Social Influence} condition, everything is identical to the
\emph{Independent} condition except that users are provided with
additional information about the number of times each song was
downloaded by other users.

\textbf{Experiment 2} is similar to \textbf{Experiment 1} except that
under the \emph{Social Influence} condition, the songs were ordered
according to the number of downloads (For the sake of simplicity, we
will ignore a minor difference in the way in which the
\emph{Independent} condition was administered). Thus, although the
information provided to users is identical under the \emph{Social
Influence} condition, in \textbf{Experiment 2} this information is
presented visually in a different manner on the website. Note that while
the randomization of treatment assignment was done within each
experiment, no randomization was used when assigning each user to one of
the two experiments because the experiments were conducted sequentially.

The researchers hypothesize that the existence of social influence
contributes to the inequality of success in music markets. According to
this hypothesis, we expect the degree of inequality to be greater under
the \emph{Social Influence} condition than the \emph{Independent}
condition within each experiment. We will analyze a portion of the
original data. The names and descriptions of variables in each data set
are shown below. Note that it is impossible to connect individual users
to the songs they listened to or downloaded from these data sets.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Data sets about songs: \texttt{songs1.csv} for \textbf{Experiment 1}
  and \texttt{songs2.csv} for \textbf{Experiment 2}
\end{enumerate}

\begin{longtable}[c]{@{}ll@{}}
\toprule\addlinespace
\begin{minipage}[b]{0.19\columnwidth}\raggedright
Name
\end{minipage} & \begin{minipage}[b]{0.75\columnwidth}\raggedright
Description
\end{minipage}
\\\addlinespace
\midrule\endhead
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{song\_id}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
Song id
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{listen\_soc}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
Number of times each song was listened to by users in the \emph{Social
Influence} condition
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{listen\_indep}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
Number of times each song was listened to by users in the
\emph{Independent} condition
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{down\_soc}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
Number of times each song was downloaded by users in the \emph{Social
Influence} condition
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.19\columnwidth}\raggedright
\texttt{down\_indep}
\end{minipage} & \begin{minipage}[t]{0.75\columnwidth}\raggedright
Number of times each song was downloaded by users in the
\emph{Independent} condition
\end{minipage}
\\\addlinespace
\bottomrule
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Data sets about users: \texttt{users1.csv} for \textbf{Experiment 1}
  and \texttt{users2.csv} for \textbf{Experiment 2}
\end{enumerate}

\begin{longtable}[c]{@{}ll@{}}
\toprule\addlinespace
\begin{minipage}[b]{0.18\columnwidth}\raggedright
Name
\end{minipage} & \begin{minipage}[b]{0.76\columnwidth}\raggedright
Description
\end{minipage}
\\\addlinespace
\midrule\endhead
\begin{minipage}[t]{0.18\columnwidth}\raggedright
\texttt{id}
\end{minipage} & \begin{minipage}[t]{0.76\columnwidth}\raggedright
User id
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.18\columnwidth}\raggedright
\texttt{world\_id}
\end{minipage} & \begin{minipage}[t]{0.76\columnwidth}\raggedright
\texttt{1} if assigned to the \emph{Social Influence} condition, and
\texttt{9} if assigned to the \emph{Independence} condition
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.18\columnwidth}\raggedright
\texttt{country\_code}
\end{minipage} & \begin{minipage}[t]{0.76\columnwidth}\raggedright
Code for user's country of residence
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.18\columnwidth}\raggedright
\texttt{country}
\end{minipage} & \begin{minipage}[t]{0.76\columnwidth}\raggedright
String for user's country of residence
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.18\columnwidth}\raggedright
\texttt{web}
\end{minipage} & \begin{minipage}[t]{0.76\columnwidth}\raggedright
User's ability to use the world wide web
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.18\columnwidth}\raggedright
\texttt{visit}
\end{minipage} & \begin{minipage}[t]{0.76\columnwidth}\raggedright
User's frequency of internet visits to consult about music or concerts
\end{minipage}
\\\addlinespace
\begin{minipage}[t]{0.18\columnwidth}\raggedright
\texttt{purchase}
\end{minipage} & \begin{minipage}[t]{0.76\columnwidth}\raggedright
\texttt{1} if user purchased a song in the past as a result after
listening to it on the web, and \texttt{0} otherwise
\end{minipage}
\\\addlinespace
\bottomrule
\end{longtable}

\subsection{Question 1}\label{question-1}

Within each experminent, compute the proportion of users assigned
separately for the \emph{Social Influence} and \emph{Independent}
condition. Summarize the results as a table of proportions for each
experiment.

\subsection{Answer 1}\label{answer-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## Load user data for each experiment}
\NormalTok{users1 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"data/users1.csv"}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{users2 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"data/users2.csv"}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{## Recode the variable with informative labels}
\NormalTok{users1$world_id[users1$world_id ==}\StringTok{ }\DecValTok{1}\NormalTok{] <-}\StringTok{ "Social Influence"}  
\NormalTok{users1$world_id[users1$world_id ==}\StringTok{ }\DecValTok{9}\NormalTok{] <-}\StringTok{ "Independent"}
\NormalTok{users2$world_id[users2$world_id ==}\StringTok{ }\DecValTok{1}\NormalTok{] <-}\StringTok{ "Social Influence"}
\NormalTok{users2$world_id[users2$world_id ==}\StringTok{ }\DecValTok{9}\NormalTok{] <-}\StringTok{ "Independent"}
\NormalTok{## Generate the proportion of users in each condition }
\NormalTok{p_exp1 <-}\StringTok{ }\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(users1$world_id))}
\NormalTok{p_exp1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      Independent Social Influence 
##        0.6724218        0.3275782
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p_exp2 <-}\StringTok{ }\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(users2$world_id))}
\NormalTok{p_exp2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      Independent Social Influence 
##        0.6772834        0.3227166
\end{verbatim}

In \textbf{Experiment 1}, the proportion of users assigned to the
\emph{Social Influence} condition was 0.328, while 0.672 where assigned
to the \emph{Independent} condition. Similarly, in \textbf{Experiment
2}, the proportion of users assigned to the \emph{Social Influence}
condition where 0.323, while 0.677 where assigned to the
\emph{Independent} condition. In both experiments, about 2/3 are
assigned to the \emph{Social Influence} condition.

\subsection{Question 2}\label{question-2}

Within each experiment, compute the \emph{average number of downloads
per user} separately for the treatment and control conditions. Note that
the number of users is different between the conditions. Comment on the
differences across the two conditions within each experiment. Repeat the
same using the number of times each song was listened to.

\subsection{Question 3}\label{question-3}

We examine the main hypothesis of the study by investigating whether
social influence increases the inequality of success in music markets.
We measure inequality using the Gini coefficient, which will be covered
in Chapter 3 of \emph{QSS} in detail. The Gini coefficient ranges from 0
(most equal) to 1 (most unequal). In the current context, the
coefficient is equal to 0 if every song has the same number of downloads
whereas it is equal to 1 if all users download the same song. To compute
this measure, we can use the \texttt{ineq()} function available in the
\textbf{ineq} package. Within each experiment, compute the Gini
coefficient separately for the \emph{Social Influence} and
\emph{Independent} conditions. Interpret the results in light of the
hypothesis. Repeat the same analysis using the number of times each song
was listened to.

\subsection{Question 4}\label{question-4}

Within each experiment, compare the characteristics of users between the
\emph{Social Influence} and \emph{Independent} conditions. In
particular, compare the mean values of \texttt{web}, \texttt{visit}, and
\texttt{purchase} variables. Interpret the results in light of the
internal validity of the conclusions you draw for each study in the
previous question.

\subsection{Question 5}\label{question-5}

Compute the difference in the estimated average effect of the
\emph{Social Influence} condition on inequality of success between the
two experiments. Under the experimental design of this study, does this
between-study comparison have as much internal validity as the
within-study comparison you conducted in Question 3? Why or Why not? Do
the data provide any information regarding the internal validity of this
between-study comparison?

\end{document}
