---
title: "The Moving to Opportunity Experiment"
output:
  pdf_document: default
  html_document: default
---

Millions of low-income Americans live in high-poverty neighborhoods, which also tend to be racially segregated and often dangerous. While social scientists have long believed that living in these neighborhoods contributes to negative outcomes for its residents, it is often difficult to establish a causal link between neighborhood conditions and individual outcomes. The Moving to Opportunity (MTO) demonstration was designed to test whether offering housing vouchers to families living in public housing in high-poverty neighborhoods could improve their lives by helping them move to lower-poverty neighborhoods. 

Between 1994 and 1998 the U.S. Department of Housing and Urban Development enrolled 4,604 low-income households from from public housing projects in Baltimore, Boston, Chicago, Los Angeles, and New York in MTO, randomly assigning enrolled families in each site to one of three groups: (1) The low-poverty voucher group received special MTO vouchers, which could only be used in census tracts with 1990 poverty rates below 10% and counseling to assist with relocation, (2) the traditional voucher group received regular section 8 vouchers, which they could use anywhere, and (3) the control group, who received no vouchers but continued to qualify for any project-based housing assistance they were entitled to receive. Today we will use the MTO data to learn if being given the opportunity to move to lower-poverty neighborhoods actually improved participants' economic and subjective wellbeing. This exercise is based on the following article:

Ludwig, J., Duncan, G.J., Gennetian, L.A., Katz, L.F., Kessler, J.R.K., and Sanbonmatsu, L., 2012. "[Neighborhood Effects on the Long-Term Well-Being of Low-Income Adults](https://dx.doi.org/10.1126/science.1224648)." *Science*, Vol. 337, Issue 6101, pp. 1505-1510.

The file `mto.csv` includes the following variables for 3,263 adult participants in the voucher and control groups:

------------------------------------------------------------------------------
 Name                             Description
 -------------------------------- ----------------------------------------------------------
 `group`                          factor with 3 levels, `lpv` (low-poverty voucher), `sec8` 
                                  (traditional section 8 voucher), and `control` 
 
 `complier`                       `1` for `lpv` and `sec8` group members who used their MTO 
                                  vouchers to relocate, `0` otherwise
                                  
 `site`                           factor with 5 levels corresponding to MTO demonstration 
                                  cities (`Baltimore`, `Boston`, `Chicago`, `Los Angeles`, 
                                  `New York`)
                                  
 `wellbeing_zscore`               Standardized measure of subjective wellbeing (happiness), 
                                  centered around control group mean and re-scaled such that 
                                  control group mean = 0 and its standard deviation = 1. Measure 
                                  is based on a 3-point happiness scale.
                                  
 `econ_ss_zcore`                  Standardized measure of economic self-sufficiency, centered 
                                  around the control group mean and re-scaled such that the control 
                                  group mean = 0 and its standard deviation = 1. Measure aggregates 
                                  several measures of economic self-sufficiency or dependency (earnings, 
                                  government transfers, employment, etc.)
------------------------------------------------------------------------------
 
The data we will use are not the original data, this dataset has been modified to protect participants' confidentiality, but the results of our analysis will be consistent with published data on the MTO demonstration. In the Science article the authors pooled the two voucher groups into a single treatment group because their outcomes converged over time. We will follow their strategy to assess the experiment's results. 

## Question 1

Did receiving MTO vouchers improve economic self-sufficiency (econ_ss_zscore) and subjective wellbeing (wellbeing_zscore) among treatment group participants?  Begin by creating a new variable `treatment` based on the `group` variable where `1` indicates membership in the `lpv` or `sec8` groups (treatment group) and `0` indicates membership in the control group.  First, test the null hypothesis that the mean subjective wellbeing variable for the treatment group is 0 with the alternative hypothesis that it is greater than 0.  Second, conduct a two-sample, two-sided hypotheses test to assess if MTO influenced economic self-sufficiency and subjective wellbeing, respectively.  Throughout this question, use 5% as the significance threshold.

## Question 2

MTO was designed to test whether *moving* from a high-poverty to a low-poverty neighborhood improved individual outcomes. But the MTO intervention only provided vouchers and counseling that would facilitate relocation for the treatment group.  It would have been unethical to force treatment group members to move and force control group members to stay where they were living. Treatment group individuals could choose not to relocate, and control group individuals could choose to relocate. About half of the participants who received MTO vouchers actually complied with the experiment by using their vouchers to move to a low-poverty neighborhood. 

Restrict the data to voucher recipients (groups `lpv` and `sec8`) and compute the proportion of compliers among the traditional section 8 voucher recipients and the low-poverty voucher recipients.  Test the hypothesis that compliance among the traditional section 8 voucher recipients was greater than among the low-poverty voucher recipients. Is the difference in proportions significant at the 5% significance level? 

## Question 3

Explore the possibility that the null result we observed for economic self-suffiency was the consequence of low compliance among voucher recipients in some MTO sites (i.e. cities). Compliance, defined as using a voucher if one is assigned to the treatment (either `lpv` or `sec8` groups), ranged from a low of 36% in Chicago to 68% in Los Angeles. Examine whether the treatment had an effect on economic self-sufficiency in Los Angeles, the MTO city with the highest compliance rate.  Specifically, conduct a two-sided t-test at the 5% significance level with the null hypothesis that the average treatment effect of MTO on economic self sufficiency for MTO participants in Los Angeles participants is zero.  Next, compute the power of this test assuming that the estimates based on this sample are equal to their true values.  Under this assumption, what is the minimum sample size necessary to detect the observed difference in economic self-sufficiency at the 95% significance level? 

## Question 4

In the Science article, the authors assessed the long-term effects of receiving an MTO housing voucher on four outcomes. Three of these outcomes were indices of economic self-sufficiency, physical health, and mental health, which allowed them to aggregate 14 separate outcomes into three domains of wellbeing. The fourth outcome was a single measure of subjective wellbeing. Thus, instead of conducting 15 separate hypothesis tests, they did only four tests. 

Assume that the authors had not aggregated these various outcomes into indices and had instead tested hypotheses for each of the 15 outcome measures they employed. At the 5% significance level, what is the probability that the authors would have rejected at least one out of 15 null hypotheses, even if all null hypotheses were true? What is the probability that they would have rejected at least 3 null hypotheses, even if all hypotheses were true? What about at the 1% significance level?  Now, compare these probabilities with the probability of rejecting at least one out of 4 true null hypothesis at the 5% and 1% significance levels. Which pitfall of hypothesis testing were the authors able to avoid with this strategy?  For this question, assume that each test is independent.

